// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHomepage } from "./plasmic/mi_2_garmin/PlasmicHomepage";
import axios from "axios";

const API_URL = 'http://localhost:5000/api';

function Homepage_(props, ref) {
  const [file, setFile] = React.useState(null);
  const [uploading, setUploading] = React.useState(false);
  const [downloading, setDownloading] = React.useState(false);
  const [sessionId, setSessionId] = React.useState(null);
  const [result, setResult] = React.useState(null);
  const [error, setError] = React.useState(null);

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.name.endsWith('.csv')) {
      setFile(selectedFile);
      setError(null);
      setResult(null);
    } else {
      setError('Please select a CSV file');
      setFile(null);
    }
  };

  const handleUpload = async () => {
    if (!file) return;

    setUploading(true);
    setError(null);
    setResult(null);

    const formData = new FormData();
    formData.append('file', file);

    try {
      const response = await axios.post(`${API_URL}/upload`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      setResult(response.data);
      setSessionId(response.data.session_id);
      setUploading(false);
    } catch (err) {
      setError(err.response?.data?.error || 'Error uploading file');
      setUploading(false);
    }
  };

  const handleDownload = async () => {
    if (!sessionId) return;

    setDownloading(true);
    try {
      const response = await axios.get(`${API_URL}/download/${sessionId}`, {
        responseType: 'blob',
      });

      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'garmin_gpx_files.zip');
      document.body.appendChild(link);
      link.click();
      link.remove();
      setDownloading(false);
    } catch (err) {
      setError('Error downloading files');
      setDownloading(false);
    }
  };

  return (
    <PlasmicHomepage
      root={{ ref }}
      {...props}
      textbox2={{
        onChange: handleFileChange,
      }}
      button={{
        onClick: handleUpload,
        disabled: !file || uploading,
      }}
      overrides={{
        textbox2: {
          props: {
            children: file ? file.name : "Choose CSV file",
          },
        },
        button: {
          props: {
            children: uploading ? "Processing..." : "Upload & Convert",
          },
        },
      }}
    />
  );
}

const Homepage = React.forwardRef(Homepage_);

export default Homepage;
