/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4eBzadHir4BZ57wPgA7u3b
// Component: BFEJzRoKSYMy
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4eBzadHir4BZ57wPgA7u3b/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import "./plasmic.css"; // plasmic-import: 4eBzadHir4BZ57wPgA7u3b/projectcss
import sty from "./PlasmicAbout.module.css"; // plasmic-import: BFEJzRoKSYMy/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    title: "About",
    openGraph: {
      title: "About"
    },
    twitter: {
      card: "summary",
      title: "About"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicAbout__VariantProps = new Array();

export const PlasmicAbout__ArgProps = new Array();

const $$ = {};

function PlasmicAbout__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_4eBzadHir4BZ57wPgA7u3b",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames("all", sty.freeBox__fe4SI)}>
            <div
              className={classNames("all", sty.freeBox__wc1Yh)}
              style={{
                webkitFontSmoothing: "antialiased",
                mozOsxFontSmoothing: "grayscale"
              }}
            >
              <div className={classNames("all", sty.freeBox__rdkZ)}>
                <div
                  className={classNames("all", "__wab_text", sty.text___6QMys)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToHomepage"] = true
                      ? (() => {
                          const actionArgs = { destination: `/` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHomepage"] != null &&
                      typeof $steps["goToHomepage"] === "object" &&
                      typeof $steps["goToHomepage"].then === "function"
                    ) {
                      $steps["goToHomepage"] = await $steps["goToHomepage"];
                    }
                  }}
                >
                  {"Homepage"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__zC5PU)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToAbout"] = true
                      ? (() => {
                          const actionArgs = { destination: `/About` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToAbout"] != null &&
                      typeof $steps["goToAbout"] === "object" &&
                      typeof $steps["goToAbout"].then === "function"
                    ) {
                      $steps["goToAbout"] = await $steps["goToAbout"];
                    }
                  }}
                >
                  {"About"}
                </div>
              </div>
              <div
                data-plasmic-name={"bigAboutBox"}
                data-plasmic-override={overrides.bigAboutBox}
                className={classNames("all", sty.bigAboutBox)}
              >
                <div className={classNames("all", sty.freeBox___8Sw3E)}>
                  <div className={classNames("all", sty.freeBox__vmiZe)}>
                    <input
                      data-plasmic-name={"textbox"}
                      data-plasmic-override={overrides.textbox}
                      accept={".csv"}
                      className={classNames(
                        "all",
                        "input",
                        "input__4eBza",
                        sty.textbox
                      )}
                      id={"file-input"}
                      onChange={async (...eventArgs) => {
                        (e => {
                          generateStateOnChangeProp($state, [
                            "textbox",
                            "value"
                          ])(e.target.value);
                        }).apply(null, eventArgs);
                      }}
                      ref={ref => {
                        $refs["textbox"] = ref;
                      }}
                      type={"file"}
                      value={
                        generateStateValueProp($state, ["textbox", "value"]) ??
                        ""
                      }
                    />
                  </div>
                </div>
                <div className={classNames("all", sty.freeBox__uKqxR)}>
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      "all",
                      "h3",
                      "h3__4eBza",
                      "__wab_text",
                      sty.h3
                    )}
                  >
                    {"Why this application?"}
                  </h3>
                  <div className={classNames("all", sty.freeBox__apjT)}>
                    <div className={classNames("all", sty.freeBox___8Lo8P)}>
                      <span
                        data-plasmic-name={"span"}
                        data-plasmic-override={overrides.span}
                        className={classNames(
                          "all",
                          "span",
                          "span__4eBza",
                          "__wab_text",
                          sty.span
                        )}
                      >
                        {
                          "My wyfe had a Mi Smartband and tracked her activitys there. Then she switched to Garmin and wanted to transfer her workloads there.\nThe first step is to as Xiaomi to send you data history that you download in CSV format.\n\nThe problem: this format is not compatoble with Garmin and all the solutions found in the market, sync apps or anything that could transfert to Garmin is not semaless or just not possibe.\n\nBut, into the CSV Mi files, there is one, usually named  \u00abXXXXXX_sport_track_data\u00bb that contains the links to every activity in GPX format. Two new problems here:\n\n- Find every link and download manually could be veeeeeery long\n- And finally the PGX format is not accepted by Garmin because the timestamp is not the right one\n\nSo, I decided to create this app than can track the CSV file, download every GPX, convert it to Garmin compatible and finally download a ZIP file with all the workloads. And bingo, you can now import them to Garmin Connect."
                        }
                      </span>
                    </div>
                  </div>
                </div>
                <div className={classNames("all", sty.freeBox__wg3J)}>
                  <div
                    className={classNames(
                      "all",
                      "__wab_text",
                      sty.text___5GkPe
                    )}
                  >
                    {"No data is keeped"}
                  </div>
                  <div
                    className={classNames("all", "__wab_text", sty.text__aJcAs)}
                  >
                    {"Free to use"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "bigAboutBox", "textbox", "h3", "span"],
  bigAboutBox: ["bigAboutBox", "textbox", "h3", "span"],
  textbox: ["textbox"],
  h3: ["h3"],
  span: ["span"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAbout__ArgProps,
          internalVariantPropNames: PlasmicAbout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    bigAboutBox: makeNodeComponent("bigAboutBox"),
    textbox: makeNodeComponent("textbox"),
    h3: makeNodeComponent("h3"),
    span: makeNodeComponent("span"),
    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/About",
      pagePath: "/About",
      params: {},
      query: {}
    })
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
