/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4eBzadHir4BZ57wPgA7u3b
// Component: GhJMU-T7IzVZ
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4eBzadHir4BZ57wPgA7u3b/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import "./plasmic.css"; // plasmic-import: 4eBzadHir4BZ57wPgA7u3b/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: GhJMU-T7IzVZ/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: o7rlW8Y_KTEE/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: xbRmki_yIZ9b/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 6iJiX8DtBr4_/icon

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_4eBzadHir4BZ57wPgA7u3b",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames("all", sty.freeBox___7Lp5W)}>
            <div
              className={classNames("all", sty.freeBox__uKrLr)}
              style={{
                webkitFontSmoothing: "antialiased",
                mozOsxFontSmoothing: "grayscale"
              }}
            >
              <div className={classNames("all", sty.freeBox__tm4E)} id={"root"}>
                <div className={classNames("all", sty.freeBox__yVdPf)}>
                  <div className={classNames("all", sty.freeBox___0WQmg)}>
                    <div className={classNames("all", sty.freeBox__zlkAx)}>
                      <div className={classNames("all", sty.freeBox__rzj5J)}>
                        <IconIcon
                          className={classNames("all", sty.svg__cnwIs)}
                          role={"img"}
                        />

                        <h1
                          data-plasmic-name={"h1"}
                          data-plasmic-override={overrides.h1}
                          className={classNames(
                            "all",
                            "h1",
                            "h1__4eBza",
                            "__wab_text",
                            sty.h1
                          )}
                        >
                          {"Mi Fitness to Garmin Converter"}
                        </h1>
                      </div>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__4eBza",
                          "__wab_text",
                          sty.h3___6Tr
                        )}
                      >
                        {"Prerequisites"}
                      </h3>
                      <p
                        data-plasmic-name={"p"}
                        data-plasmic-override={overrides.p}
                        className={classNames(
                          "all",
                          "p",
                          "p__4eBza",
                          "__wab_text",
                          sty.p
                        )}
                      >
                        {
                          "You already request Xiaomi a download of your fitness history by logging into your Xiaomi cloud account via a web browser.\n\nYou already have you located the file tht contains the links (usally named \u00abXXXXXX_sport_track_data.csv\u00bb"
                        }
                      </p>
                    </div>
                    <div className={classNames("all", sty.freeBox__cbxY)}>
                      <div className={classNames("all", sty.freeBox__h5ZhD)}>
                        <input
                          data-plasmic-name={"textbox2"}
                          data-plasmic-override={overrides.textbox2}
                          accept={".csv"}
                          className={classNames(
                            "all",
                            "input",
                            "input__4eBza",
                            sty.textbox2
                          )}
                          id={"file-input"}
                          onChange={async (...eventArgs) => {
                            (e => {
                              generateStateOnChangeProp($state, [
                                "textbox2",
                                "value"
                              ])(e.target.value);
                            }).apply(null, eventArgs);
                          }}
                          ref={ref => {
                            $refs["textbox2"] = ref;
                          }}
                          type={"file"}
                          value={
                            generateStateValueProp($state, [
                              "textbox2",
                              "value"
                            ]) ?? ""
                          }
                        />

                        <label
                          data-plasmic-name={"label"}
                          data-plasmic-override={overrides.label}
                          className={classNames("all", sty.label)}
                          for={"file-input"}
                        >
                          <Icon2Icon
                            className={classNames("all", sty.svg__fYcDf)}
                            role={"img"}
                          />

                          <span
                            className={classNames(
                              "all",
                              "span",
                              "span__4eBza",
                              "__wab_text",
                              sty.span__pxh5T
                            )}
                            style={{ textOverflow: "ellipsis" }}
                          >
                            {
                              "20260612_6779095247_MiFitness_hlth_center_sport_track_data.csv"
                            }
                          </span>
                        </label>
                      </div>
                      <button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames(
                          "all",
                          "button",
                          "button__4eBza",
                          sty.button
                        )}
                        disabled={""}
                      >
                        <Icon3Icon
                          className={classNames("all", sty.svg___7FY)}
                          role={"img"}
                        />

                        <span
                          className={classNames(
                            "all",
                            "span",
                            "span__4eBza",
                            "__wab_text",
                            sty.span___2RW6M
                          )}
                        >
                          {"Processing..."}
                        </span>
                      </button>
                    </div>
                    <div className={classNames("all", sty.freeBox__djgIo)}>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__4eBza",
                          "__wab_text",
                          sty.h3__dI9X
                        )}
                      >
                        {"Instructions:"}
                      </h3>
                      <div className={classNames("all", sty.freeBox__t6Wab)}>
                        <div className={classNames("all", sty.freeBox__lj5Wc)}>
                          <span
                            className={classNames(
                              "all",
                              "span",
                              "span__4eBza",
                              "__wab_text",
                              sty.span__aflEm
                            )}
                          >
                            {
                              "Upload a CSV file containing GPX file URLs in the 'GPX' column"
                            }
                          </span>
                        </div>
                        <div className={classNames("all", sty.freeBox__pwoda)}>
                          <span
                            className={classNames(
                              "all",
                              "span",
                              "span__4eBza",
                              "__wab_text",
                              sty.span___2VyNc
                            )}
                          >
                            {
                              "The system will automatically download all GPX files"
                            }
                          </span>
                        </div>
                        <div className={classNames("all", sty.freeBox__mn8Ut)}>
                          <span
                            className={classNames(
                              "all",
                              "span",
                              "span__4eBza",
                              "__wab_text",
                              sty.span___6BkYq
                            )}
                          >
                            {
                              "Each file is converted to Garmin-compatible format with continuous timestamps"
                            }
                          </span>
                        </div>
                        <div className={classNames("all", sty.freeBox__ly9Ge)}>
                          <span
                            className={classNames(
                              "all",
                              "span",
                              "span__4eBza",
                              "__wab_text",
                              sty.span___0U8Qz
                            )}
                          >
                            {
                              "Download the ZIP file containing all converted GPX files"
                            }
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={classNames("all", sty.freeBox___6O2M4)}>
                    <div className={classNames("all", sty.freeBox__mD4Fw)}>
                      <div className={classNames("all", sty.freeBox__eOnuT)}>
                        <input
                          data-plasmic-name={"textbox"}
                          data-plasmic-override={overrides.textbox}
                          accept={".csv"}
                          className={classNames(
                            "all",
                            "input",
                            "input__4eBza",
                            sty.textbox
                          )}
                          id={"file-input"}
                          onChange={async (...eventArgs) => {
                            (e => {
                              generateStateOnChangeProp($state, [
                                "textbox",
                                "value"
                              ])(e.target.value);
                            }).apply(null, eventArgs);
                          }}
                          ref={ref => {
                            $refs["textbox"] = ref;
                          }}
                          type={"file"}
                          value={
                            generateStateValueProp($state, [
                              "textbox",
                              "value"
                            ]) ?? ""
                          }
                        />
                      </div>
                    </div>
                    <div className={classNames("all", sty.freeBox___5G8QP)}>
                      <h3
                        className={classNames(
                          "all",
                          "h3",
                          "h3__4eBza",
                          "__wab_text",
                          sty.h3__cn2PO
                        )}
                      >
                        {"Why this application?"}
                      </h3>
                      <div className={classNames("all", sty.freeBox___4VedD)}>
                        <div className={classNames("all", sty.freeBox___8EHw)}>
                          <span
                            className={classNames(
                              "all",
                              "span",
                              "span__4eBza",
                              "__wab_text",
                              sty.span__sVfMv
                            )}
                          >
                            {
                              "My wyfe had a Mi Smartband and tracked her activitys there. Then she switched to Garmin and wanted to transfer her workloads there.\nThe first step is to as Xiaomi to send you data history that you download in CSV format.\n\nThe problem: this format is not compatoble with Garmin and all the solutions found in the market, sync apps or anything that could transfert to Garmin is not semaless or just not possibe.\n\nBut, into the CSV Mi files, there is one, usually named  \u00abXXXXXX_sport_track_data\u00bb that contains the links to every activity in GPX format. Two problems here:\n\n- Find every link and download manually could be veeeeeery long\n- And finally the PGX format is not accepted by Garmin because the timestamp is not the right one\n\nSo, I decided to create this app than can track the CSV file, download every GPX, convert it to Garmin compatible and finally download a ZIP file with all the workloads. And bingo, you can now import them to Garmin Connect."
                            }
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "h1", "p", "textbox2", "label", "button", "textbox"],
  h1: ["h1"],
  p: ["p"],
  textbox2: ["textbox2"],
  label: ["label"],
  button: ["button"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    p: makeNodeComponent("p"),
    textbox2: makeNodeComponent("textbox2"),
    label: makeNodeComponent("label"),
    button: makeNodeComponent("button"),
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
