/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4eBzadHir4BZ57wPgA7u3b
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4eBzadHir4BZ57wPgA7u3b/projectModule
import "./plasmic.css"; // plasmic-import: 4eBzadHir4BZ57wPgA7u3b/projectcss

const data = {
  base: `${"plasmic_tokens_4eBzadHir4BZ57wPgA7u3b"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
